<?php
/**
 * <DZCP-Extended Edition>
 * @package: DZCP-Extended Edition
 * @author: DZCP Developer Team || Hammermaps.de Developer Team
 * @link: http://www.dzcp.de || http://www.hammermaps.de
 */

if(_adminMenu != 'true') exit();

if(isset($_POST))
{
	if(convert::ToString($_POST['cache_engine']) != $cache_engine)
		$cache_cleanup = true;

            db("UPDATE ".dba::get('config')." SET
                `upicsize`           = '".convert::ToInt($_POST['m_upicsize'])."',
                `m_gallery`          = '".convert::ToInt($_POST['m_gallery'])."',
                `m_gallerypics`      = '".convert::ToInt($_POST['m_gallerypics'])."',
                `m_usergb`           = '".convert::ToInt($_POST['m_usergb'])."',
                `m_artikel`          = '".convert::ToInt($_POST['m_artikel'])."',
                `m_adminartikel`     = '".convert::ToInt($_POST['m_adminartikel'])."',
                `m_clanwars`         = '".convert::ToInt($_POST['m_clanwars'])."',
                `m_awards`           = '".convert::ToInt($_POST['m_awards'])."',
                `allowhover`         = '".convert::ToInt($_POST['ahover'])."',
                `securelogin`        = '".convert::ToInt($_POST['securelogin'])."',
                `m_clankasse`        = '".convert::ToInt($_POST['m_clankasse'])."',
                `m_userlist`         = '".convert::ToInt($_POST['m_userlist'])."',
                `m_adminnews`        = '".convert::ToInt($_POST['m_adminnews'])."',
                `l_servernavi`       = '".convert::ToInt($_POST['l_servernavi'])."',
                `l_shoutnick`        = '".convert::ToInt($_POST['l_shoutnick'])."',
                `m_gb`               = '".convert::ToInt($_POST['m_gb'])."',
                `m_fthreads`         = '".convert::ToInt($_POST['m_fthreads'])."',
                `m_fposts`           = '".convert::ToInt($_POST['m_fposts'])."',
                `gallery`            = '".convert::ToInt($_POST['m_gallery_user'])."',
                `m_news`             = '".convert::ToInt($_POST['m_news'])."',
                `m_shout`            = '".convert::ToInt($_POST['m_shout'])."',
                `m_comments`         = '".convert::ToInt($_POST['m_comments'])."',
                `m_archivnews`       = '".convert::ToInt($_POST['m_archivnews'])."',
                `maxwidth`           = '".convert::ToInt($_POST['maxwidth'])."',
                `f_forum`            = '".convert::ToInt($_POST['f_forum'])."',
                `f_cwcom`            = '".convert::ToInt($_POST['f_cwcom'])."',
                `f_gb`               = '".convert::ToInt($_POST['f_gb'])."',
                `f_artikelcom`       = '".convert::ToInt($_POST['f_artikelcom'])."',
                `f_membergb`         = '".convert::ToInt($_POST['f_membergb'])."',
                `f_shout`            = '".convert::ToInt($_POST['f_shout'])."',
                `f_newscom`          = '".convert::ToInt($_POST['f_newscom'])."',
                `f_downloadcom`      = '".convert::ToInt($_POST['f_downloadcom'])."',
                `l_newsadmin`        = '".convert::ToInt($_POST['l_newsadmin'])."',
                `l_shouttext`        = '".convert::ToInt($_POST['l_shouttext'])."',
                `l_newsarchiv`       = '".convert::ToInt($_POST['l_newsarchiv'])."',
                `l_forumtopic`       = '".convert::ToInt($_POST['l_forumtopic'])."',
                `l_forumsubtopic`    = '".convert::ToInt($_POST['l_forumsubtopic'])."',
                `l_clanwars`         = '".convert::ToInt($_POST['l_clanwars'])."',
                `m_lnews`            = '".convert::ToInt($_POST['m_lnews'])."',
                `m_lartikel`         = '".convert::ToInt($_POST['m_lartikel'])."',
                `m_events`           = '".convert::ToInt($_POST['m_events'])."',
                `m_topdl`            = '".convert::ToInt($_POST['m_topdl'])."',
                `m_ftopics`          = '".convert::ToInt($_POST['m_ftopics'])."',
                `m_cwcomments`       = '".convert::ToInt($_POST['m_cwcomments'])."',
                `m_lwars`            = '".convert::ToInt($_POST['m_lwars'])."',
                `m_lreg`             = '".convert::ToInt($_POST['m_lreg'])."',
                `m_nwars`            = '".convert::ToInt($_POST['m_nwars'])."',
                `l_topdl`            = '".convert::ToInt($_POST['l_topdl'])."',
                `l_ftopics`          = '".convert::ToInt($_POST['l_ftopics'])."',
                `l_lreg`             = '".convert::ToInt($_POST['l_lreg'])."',
                `l_lnews`            = '".convert::ToInt($_POST['l_lnews'])."',
                `l_lartikel`         = '".convert::ToInt($_POST['l_lartikel'])."',
                `l_lwars`            = '".convert::ToInt($_POST['l_lwars'])."',
                `teamrow`            = '".convert::ToInt($_POST['teamrow'])."',
                `shout_max_zeichen`  = '".convert::ToInt($_POST['zeichen'])."',
                `maxshoutarchiv`     = '".convert::ToInt($_POST['m_shouta'])."',
                `m_away`             = '".convert::ToInt($_POST['m_away'])."',
                `direct_refresh`     = '".convert::ToInt($_POST['direct_refresh'])."',
                `cache_teamspeak`    = '".convert::ToInt($_POST['cache_teamspeak'])."',
                `cache_server`       = '".convert::ToInt($_POST['cache_server'])."',
                `cache_news`         = '".convert::ToInt($_POST['cache_news'])."',
                `cache_engine`       = '".string::encode($_POST['cache_engine'])."',
                `l_nwars`            = '".convert::ToInt($_POST['l_nwars'])."',
                `news_feed`   	     = '".convert::ToInt($_POST['feed'])."',
                `use_akl`   	     = '".convert::ToInt($_POST['akl'])."'
            WHERE id = 1");

            db("UPDATE ".dba::get('settings')." SET
                `clanname`              = '".string::encode($_POST['clanname'])."',
                `pagetitel`             = '".string::encode($_POST['pagetitel'])."',
                `badwords`              = '".string::encode($_POST['badwords'])."',
                `gmaps_who`             = '".convert::ToInt($_POST['gmaps_who'])."',
                `language`              = '".string::encode($_POST['language'])."',
                `regcode`               = '".convert::ToInt($_POST['regcode'])."',
                `forum_vote`            = '".convert::ToInt($_POST['forum_vote'])."',
                `reg_forum`             = '".convert::ToInt($_POST['reg_forum'])."',
                `reg_artikel`           = '".convert::ToInt($_POST['reg_artikel'])."',
                `reg_shout`             = '".convert::ToInt($_POST['reg_shout'])."',
                `reg_cwcomments`        = '".convert::ToInt($_POST['reg_cwcomments'])."',
                `reg_newscomments`      = '".convert::ToInt($_POST['reg_nc'])."',
                `reg_dl`                = '".convert::ToInt($_POST['reg_dl'])."',
                `reg_dlcomments`        = '".convert::ToInt($_POST['reg_dlcomments'])."',
                `eml_reg_subj`          = '".string::encode($_POST['eml_reg_subj'])."',
                `eml_pwd_subj`          = '".string::encode($_POST['eml_pwd_subj'])."',
                `eml_nletter_subj`      = '".string::encode($_POST['eml_nletter_subj'])."',
                `eml_pn_subj`           = '".string::encode($_POST['eml_pn_subj'])."',
                `double_post`           = '".convert::ToInt($_POST['double_post'])."',
                `gb_activ`              = '".convert::ToInt($_POST['gb_activ'])."',
                `eml_fabo_npost_subj`   = '".string::encode($_POST['eml_fabo_npost_subj'])."',
                `eml_fabo_tedit_subj`   = '".string::encode($_POST['eml_fabo_tedit_subj'])."',
                `eml_fabo_pedit_subj`   = '".string::encode($_POST['eml_fabo_pedit_subj'])."',
                `eml_akl_register_subj` = '".string::encode($_POST['eml_akl_regist_subj'])."',
                `eml_reg`               = '".string::encode($_POST['eml_reg'])."',
                `eml_pwd`               = '".string::encode($_POST['eml_pwd'])."',
                `eml_nletter`           = '".string::encode($_POST['eml_nletter'])."',
                `eml_pn`        	    = '".string::encode($_POST['eml_pn'])."',
                `eml_fabo_npost`        = '".string::encode($_POST['eml_fabo_npost'])."',
                `eml_fabo_tedit`        = '".string::encode($_POST['eml_fabo_tedit'])."',
                `eml_fabo_pedit`        = '".string::encode($_POST['eml_fabo_pedit'])."',
                `eml_akl_register`      = '".string::encode($_POST['eml_akl_regist'])."',
                `mailfrom`              = '".string::encode($_POST['mailfrom'])."',
                `tmpdir`                = '".string::encode($_POST['tmpdir'])."',
                `persinfo`              = '".convert::ToInt($_POST['persinfo'])."',
                `wmodus`                = '".convert::ToInt($_POST['wmodus'])."',
                `mail_extension`        = '".string::encode($_POST['mail_extension'])."',
                `smtp_password`         = '".encryptData($_POST['smtp_pass'])."',
                `smtp_port`             = '".convert::ToInt($_POST['smtp_port'])."',
                `smtp_hostname`         = '".string::encode($_POST['smtp_host'])."',
                `smtp_username`         = '".string::encode($_POST['smtp_username'])."',
                `smtp_tls_ssl`          = '".convert::ToInt($_POST['smtp_tls_ssl'])."',
                `sendmail_path`         = '".string::encode($_POST['sendmail_path'])."',
                `memcache_host`         = '".string::encode($_POST['memcache_host'])."',
                `memcache_port`         = '".convert::ToInt($_POST['memcache_port'])."',
                `urls_linked`   	    = '".string::encode($_POST['urls_linked'])."'
            WHERE id = 1");

            $show = info(_config_set, "?admin=config", 10);
        }